In [1]:
#Load the dataset
import pandas as pd
import numpy as np
pd.read_csv('C:/Users/varsh/Downloads/data/Hospital General Information.csv', engine = 'python')
df =pd.read_csv ('C:/Users/varsh/Downloads/data/Hospital General Information.csv',engine='python')
df.head(20)

,Provider ID,Hospital Name,Address,City,State,ZIP Code,County Name,Phone Number,Hospital Type,Hospital Ownership,...,Readmission national comparison,Readmission national comparison footnote,Patient experience national comparison,Patient experience national comparison footnote,Effectiveness of care national comparison,Effectiveness of care national comparison footnote,Timeliness of care national comparison,Timeliness of care national comparison footnote,Efficient use of medical imaging national comparison,Efficient use of medical imaging national comparison footnote
0,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,3347938701,Acute Care Hospitals,Government - Hospital District or Authority,...,Same as the national average,NaN,Below the national average,NaN,Same as the national average,NaN,Same as the national average,NaN,Same as the national average,NaN
1,10005,MARSHALL MEDICAL CENTER SOUTH,2505 U S HIGHWAY 431 NORTH,BOAZ,AL,35957,MARSHALL,2565938310,Acute Care Hospitals,Government - Hospital District or Authority,...,Above the national average,NaN,Same as the national average,NaN,Same as the national average,NaN,Above the national average,NaN,Below the national average,NaN
2,10006,ELIZA COFFEE MEMORIAL HOSPITAL,205 MARENGO STREET,FLORENCE,AL,35631,LAUDERDALE,2567688400,Acute Care Hospitals,Government - Hospital District or Authority,...,Same as the national average,NaN,Below the national average,NaN,Same as the national average,NaN,Above the national average,NaN,Same as the national average,NaN
3,10007,MIZELL MEMORIAL HOSPITAL,702 N MAIN ST,OPP,AL,36467,COVINGTON,3344933541,Acute Care Hospitals,Voluntary non-profit - Private,...,Below the national average,NaN,Same as the national average,NaN,Below the national average,NaN,Above the national average,NaN,Not Available,Results are not available for this reporting p...
4,10008,CRENSHAW COMMUNITY HOSPITAL,101 HOSPITAL CIRCLE,LUVERNE,AL,36049,CRENSHAW,3343353374,Acute Care Hospitals,Proprietary,...,Same as the national average,NaN,Not Available,Results are not available for this reporting p...,Same as the national average,NaN,Above the national average,NaN,Not Available,Results are not available for this reporting p...
5,10011,ST VINCENT'S EAST,50 MEDICAL PARK EAST DRIVE,BIRMINGHAM,AL,35235,JEFFERSON,2058383122,Acute Care Hospitals,Voluntary non-profit - Private,...,Same as the national average,NaN,Below the national average,NaN,Below the national average,NaN,Same as the national average,NaN,Same as the national average,NaN
6,10012,DEKALB REGIONAL MEDICAL CENTER,200 MED CENTER DRIVE,FORT PAYNE,AL,35968,DE KALB,2568453150,Acute Care Hospitals,Proprietary,...,Same as the national average,NaN,Same as the national average,NaN,Same as the national average,NaN,Above the national average,NaN,Same as the national average,NaN
7,10016,SHELBY BAPTIST MEDICAL CENTER,1000 FIRST STREET NORTH,ALABASTER,AL,35007,SHELBY,2056208100,Acute Care Hospitals,Voluntary non-profit - Private,...,Above the national average,NaN,Below the national average,NaN,Same as the national average,NaN,Below the national average,NaN,Below the national average,NaN
8,10018,CALLAHAN EYE HOSPITAL,1720 UNIVERSITY BLVD,BIRMINGHAM,AL,35233,JEFFERSON,2053258100,Acute Care Hospitals,Voluntary non-profit - Private,...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Same as the national average,NaN,Same as the national average,NaN,Not Available,Results are not available for this reporting p...
9,10019,HELEN KELLER MEMORIAL HOSPITAL,1300 SOUTH MONTGOMERY AVENUE,SHEFFIELD,AL,35660,COLBERT,2563864556,Acute Care Hospitals,Government - Hospital District or Authority,...,Below the national average,NaN,Below the national average,NaN,Same as the national average,NaN,Above the national average,NaN,Below the national average,NaN
10,10021,DALE MEDICAL CENTER,126 HOSPITAL AVE,OZARK,AL,36360,DALE,3347742601,Acute Care Hospitals,Government - Hospital District or Authority,...,Same as the national average,NaN,Above the national average,NaN,Same as the national average,NaN,Above the national average,NaN,Same as the national average,NaN
11,10022,CHEROKEE MEDICAL CENTER,400 NORTHWOOD DR,CENTRE,AL,35960,CHEROKEE,2569275531,Acute Care Hospitals,Voluntary non-profit - Private,...,Same as the national average,NaN,Above the national average,NaN,Same as the national average,NaN,Same as the national average,NaN,Not Available,Results are not available for this reporting p...
12,10023,BAPTIST MEDICAL CENTER SOUTH,2105 EAST SOUTH BOULEVARD,MONTGOMERY,AL,36116,MONTGOMERY,3342882100,Acute Care Hospitals,Government - Hospital District or Authority,...,Same as the national average,NaN,Below the national average,NaN,Same as the national average,NaN,Below the national average,NaN,Above the national average,NaN
13,10024,JACKSON HOSPITAL & CLINIC INC,1725 PINE STREET,MONTGOMERY,AL,36106,MONTGOMERY,3342938000,Acute Care Hospitals,Voluntary non-profit - Private,...,Above the national average,NaN,Same as the national average,NaN,Same as the national average,NaN,Below the national average,NaN,Same as the national average,NaN
14,10029,EAST ALABAMA MEDICAL CENTER,2000 PEPPERELL PARKWAY,OPELIKA,AL,36801,LEE,3347493411,Acute Care Hospitals,Government - Hospital District or Authority,...,Above the national average,NaN,Above the national average,NaN,Same as the national average,NaN,Above the national average,NaN,Same as the national average,NaN
15,10032,WEDOWEE HOSPITAL,209 NORTH MAIN STREET,WEDOWEE,AL,36278,RANDOLPH,2563572111,Acute Care Hospitals,Government - Hospital District or Authority,...,Same as the national average,NaN,Not Available,Results are not available for this reporting p...,Same as the national average,NaN,Same as the national average,NaN,Not Available,Results are not available for this reporting p...
16,10033,UNIVERSITY OF ALABAMA HOSPITAL,619 SOUTH 19TH STREET,BIRMINGHAM,AL,35233,JEFFERSON,2059344011,Acute Care Hospitals,Government - State,...,Below the national average,NaN,Above the national average,NaN,Same as the national average,NaN,Below the national average,NaN,Below the national average,NaN
17,10034,COMMUNITY HOSPITAL INC,805 FRIENDSHIP ROAD,TALLASSEE,AL,36078,ELMORE,3342836541,Acute Care Hospitals,Voluntary non-profit - Private,...,Same as the national average,NaN,Same as the national average,NaN,Same as the national average,NaN,Same as the national average,NaN,Not Available,Results are not available for this reporting p...
18,10035,CULLMAN REGIONAL MEDICAL CENTER,1912 ALABAMA HIGHWAY 157,CULLMAN,AL,35058,CULLMAN,2567372000,Acute Care Hospitals,Government - Hospital District or Authority,...,Same as the national average,NaN,Same as the national average,NaN,Same as the national average,NaN,Above the national average,NaN,Same as the national average,NaN
19,10036,ANDALUSIA REGIONAL HOSPITAL,849 SOUTH THREE NOTCH STREET,ANDALUSIA,AL,36420,COVINGTON,3342228466,Acute Care Hospitals,Proprietary,...,Below the national average,NaN,Below the national average,NaN,Same as the national average,NaN,Above the national average,NaN,Same as the national average,NaN

In [2]:
df.isnull().sum()

Provider ID                                                         0
Hospital Name                                                       0
Address                                                             0
City                                                                0
State                                                               0
ZIP Code                                                            0
County Name                                                        15
Phone Number                                                        0
Hospital Type                                                       0
Hospital Ownership                                                  0
Emergency Services                                                  0
Meets criteria for meaningful use of EHRs                         143
Hospital overall rating                                             0
Hospital overall rating footnote                                 3414
Mortality national comparison                                       0
Mortality national comparison footnote                           3460
Safety of care national comparison                                  0
Safety of care national comparison footnote                      2644
Readmission national comparison                                     0
Readmission national comparison footnote                         3795
Patient experience national comparison                              0
Patient experience national comparison footnote                  3443
Effectiveness of care national comparison                           0
Effectiveness of care national comparison footnote               3610
Timeliness of care national comparison                              0
Timeliness of care national comparison footnote                  3546
Efficient use of medical imaging national comparison                0
Efficient use of medical imaging national comparison footnote    2779
dtype: int64

In [3]:
df.describe()

         Provider ID      ZIP Code  Phone Number
count    4812.000000   4812.000000  4.812000e+03
mean   268294.422901  53990.132377  5.849100e+09
std    157109.340215  26915.916870  2.331563e+09
min     10001.000000    603.000000  9.369338e+08
25%    140185.750000  33015.250000  4.015615e+09
50%    260043.500000  55410.500000  6.053413e+09
75%    390222.250000  76035.500000  7.877574e+09
max    670118.000000  99929.000000  9.898943e+09

In [4]:
dropcolumn = list(df.filter(regex='footnote'))
df_clean = df[df.columns.drop(dropcolumn)]
df_clean.head()

,Provider ID,Hospital Name,Address,City,State,ZIP Code,County Name,Phone Number,Hospital Type,Hospital Ownership,Emergency Services,Meets criteria for meaningful use of EHRs,Hospital overall rating,Mortality national comparison,Safety of care national comparison,Readmission national comparison,Patient experience national comparison,Effectiveness of care national comparison,Timeliness of care national comparison,Efficient use of medical imaging national comparison
0,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,3347938701,Acute Care Hospitals,Government - Hospital District or Authority,Yes,Y,3,Same as the national average,Above the national average,Same as the national average,Below the national average,Same as the national average,Same as the national average,Same as the national average
1,10005,MARSHALL MEDICAL CENTER SOUTH,2505 U S HIGHWAY 431 NORTH,BOAZ,AL,35957,MARSHALL,2565938310,Acute Care Hospitals,Government - Hospital District or Authority,Yes,Y,3,Below the national average,Same as the national average,Above the national average,Same as the national average,Same as the national average,Above the national average,Below the national average
2,10006,ELIZA COFFEE MEMORIAL HOSPITAL,205 MARENGO STREET,FLORENCE,AL,35631,LAUDERDALE,2567688400,Acute Care Hospitals,Government - Hospital District or Authority,Yes,Y,2,Below the national average,Same as the national average,Same as the national average,Below the national average,Same as the national average,Above the national average,Same as the national average
3,10007,MIZELL MEMORIAL HOSPITAL,702 N MAIN ST,OPP,AL,36467,COVINGTON,3344933541,Acute Care Hospitals,Voluntary non-profit - Private,Yes,Y,2,Same as the national average,Not Available,Below the national average,Same as the national average,Below the national average,Above the national average,Not Available
4,10008,CRENSHAW COMMUNITY HOSPITAL,101 HOSPITAL CIRCLE,LUVERNE,AL,36049,CRENSHAW,3343353374,Acute Care Hospitals,Proprietary,Yes,Y,3,Same as the national average,Not Available,Same as the national average,Not Available,Same as the national average,Above the national average,Not Available

In [5]:
new_df= df_clean.replace('Not Available', np.nan )
new_df

,Provider ID,Hospital Name,Address,City,State,ZIP Code,County Name,Phone Number,Hospital Type,Hospital Ownership,Emergency Services,Meets criteria for meaningful use of EHRs,Hospital overall rating,Mortality national comparison,Safety of care national comparison,Readmission national comparison,Patient experience national comparison,Effectiveness of care national comparison,Timeliness of care national comparison,Efficient use of medical imaging national comparison
0,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,3347938701,Acute Care Hospitals,Government - Hospital District or Authority,Yes,Y,3,Same as the national average,Above the national average,Same as the national average,Below the national average,Same as the national average,Same as the national average,Same as the national average
1,10005,MARSHALL MEDICAL CENTER SOUTH,2505 U S HIGHWAY 431 NORTH,BOAZ,AL,35957,MARSHALL,2565938310,Acute Care Hospitals,Government - Hospital District or Authority,Yes,Y,3,Below the national average,Same as the national average,Above the national average,Same as the national average,Same as the national average,Above the national average,Below the national average
2,10006,ELIZA COFFEE MEMORIAL HOSPITAL,205 MARENGO STREET,FLORENCE,AL,35631,LAUDERDALE,2567688400,Acute Care Hospitals,Government - Hospital District or Authority,Yes,Y,2,Below the national average,Same as the national average,Same as the national average,Below the national average,Same as the national average,Above the national average,Same as the national average
3,10007,MIZELL MEMORIAL HOSPITAL,702 N MAIN ST,OPP,AL,36467,COVINGTON,3344933541,Acute Care Hospitals,Voluntary non-profit - Private,Yes,Y,2,Same as the national average,NaN,Below the national average,Same as the national average,Below the national average,Above the national average,NaN
4,10008,CRENSHAW COMMUNITY HOSPITAL,101 HOSPITAL CIRCLE,LUVERNE,AL,36049,CRENSHAW,3343353374,Acute Care Hospitals,Proprietary,Yes,Y,3,Same as the national average,NaN,Same as the national average,NaN,Same as the national average,Above the national average,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4807,670118,FIRST TEXAS HOSPITAL,9922 LOUETTA RD,HOUSTON,TX,77070,HARRIS,8442641435,Acute Care Hospitals,Proprietary,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4808,640001,LBJ TROPICAL MEDICAL CENTER,FAGAALU VILLAGE,PAGO PAGO,AS,96799,NaN,6846334590,Acute Care Hospitals,Government - Hospital District or Authority,Yes,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4809,650001,GUAM MEMORIAL HOSPITAL AUTHORITY,85O GOV CARLOS G CAMACHO ROAD,TAMUNING,GU,96913,NaN,6716472552,Acute Care Hospitals,Government - Local,Yes,Y,3,Below the national average,NaN,Same as the national average,NaN,Same as the national average,NaN,NaN
4810,650003,GUAM REGIONAL MEDICAL CITY,133 ROUTE 3,DEDEDO,GU,96929,NaN,6716455500,Acute Care Hospitals,Voluntary non-profit - Private,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4811,660001,COMMONWEALTH HEALTH CENTER,"PO BOX 409CK, NAVY HILL ROAD",GARAPAN,MP,96950,NaN,6702348950,Acute Care Hospitals,Proprietary,Yes,Y,NaN,Same as the national average,NaN,Below the national average,NaN,NaN,NaN,NaN

In [6]:
#converting to numerial values
ordinal_col = list(new_df.filter(regex="national comparison"))

mapper = {
    'Below the national average' : 0,
    'Same as the national average' : 1, 
    'Above the national average' : 2
}
for col in ordinal_col:
    new_df.loc[:, new_df.columns == col]= new_df.loc[:, new_df.columns == col].replace(mapper)
new_df.head()

,Provider ID,Hospital Name,Address,City,State,ZIP Code,County Name,Phone Number,Hospital Type,Hospital Ownership,Emergency Services,Meets criteria for meaningful use of EHRs,Hospital overall rating,Mortality national comparison,Safety of care national comparison,Readmission national comparison,Patient experience national comparison,Effectiveness of care national comparison,Timeliness of care national comparison,Efficient use of medical imaging national comparison
0,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,3347938701,Acute Care Hospitals,Government - Hospital District or Authority,Yes,Y,3,1.0,2.0,1.0,0.0,1.0,1.0,1.0
1,10005,MARSHALL MEDICAL CENTER SOUTH,2505 U S HIGHWAY 431 NORTH,BOAZ,AL,35957,MARSHALL,2565938310,Acute Care Hospitals,Government - Hospital District or Authority,Yes,Y,3,0.0,1.0,2.0,1.0,1.0,2.0,0.0
2,10006,ELIZA COFFEE MEMORIAL HOSPITAL,205 MARENGO STREET,FLORENCE,AL,35631,LAUDERDALE,2567688400,Acute Care Hospitals,Government - Hospital District or Authority,Yes,Y,2,0.0,1.0,1.0,0.0,1.0,2.0,1.0
3,10007,MIZELL MEMORIAL HOSPITAL,702 N MAIN ST,OPP,AL,36467,COVINGTON,3344933541,Acute Care Hospitals,Voluntary non-profit - Private,Yes,Y,2,1.0,NaN,0.0,1.0,0.0,2.0,NaN
4,10008,CRENSHAW COMMUNITY HOSPITAL,101 HOSPITAL CIRCLE,LUVERNE,AL,36049,CRENSHAW,3343353374,Acute Care Hospitals,Proprietary,Yes,Y,3,1.0,NaN,1.0,NaN,1.0,2.0,NaN

In [41]:
DF = new_df.dropna()

In [76]:
noduplicate = DF.drop_duplicates(['Provider ID','ZIP Code'])
utility_value = DF.pivot_table(values='Hospital overall rating', index='ZIP Code', columns='Provider ID', aggfunc='first',fill_value=0)
utility_value.head()

Provider ID,10001,10005,10006,10011,10012,10016,10019,10021,10023,10024,...,670047,670055,670056,670060,670068,670077,670079,670080,670082,670088
ZIP Code,,,,,,,,,,,,,,,,,,,,,
1040,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1060,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1085,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1104,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1199,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [77]:
utility_value.shape

(2172, 2297)

In [78]:
X1 = utility_value.T
X1.head()

ZIP Code,1040,1060,1085,1104,1199,1201,1301,1432,1440,1453,...,99204,99208,99210,99216,99336,99352,99362,99508,99645,99701
Provider ID,,,,,,,,,,,,,,,,,,,,,
10001,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10005,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10006,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10011,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10012,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [79]:
X1.shape

(2297, 2172)

In [80]:
X=X1

In [81]:
#converting to truncated SVD
import sklearn
from sklearn.decomposition import TruncatedSVD

SVD = TruncatedSVD(n_components=10)

# model fitting
decomposed_matrix = SVD.fit_transform(X1)
decomposed_matrix.shape

(2297, 10)

In [82]:
correlation_matrix = np.corrcoef(decomposed_matrix)
correlation_matrix.shape

(2297, 2297)

In [83]:
X1.index[60]

30016

In [84]:
i = 30016

provider_id = list(X1.index)
provider_id

[10001,
 10005,
 10006,
 10011,
 10012,
 10016,
 10019,
 10021,
 10023,
 10024,
 10029,
 10033,
 10035,
 10036,
 10038,
 10039,
 10040,
 10046,
 10049,
 10055,
 10056,
 10061,
 10065,
 10078,
 10079,
 10083,
 10085,
 10086,
 10087,
 10089,
 10090,
 10092,
 10100,
 10103,
 10104,
 10108,
 10113,
 10114,
 10118,
 10126,
 10130,
 10131,
 10139,
 10144,
 10149,
 10150,
 10157,
 10158,
 10164,
 20001,
 20006,
 20012,
 30002,
 30006,
 30007,
 30010,
 30011,
 30012,
 30013,
 30014,
 30016,
 30023,
 30024,
 30033,
 30036,
 30038,
 30043,
 30055,
 30061,
 30062,
 30064,
 30065,
 30068,
 30069,
 30085,
 30087,
 30088,
 30089,
 30092,
 30093,
 30101,
 30103,
 30110,
 30111,
 30114,
 30115,
 30117,
 30119,
 30121,
 30122,
 30123,
 40004,
 40007,
 40010,
 40014,
 40016,
 40017,
 40020,
 40022,
 40026,
 40027,
 40029,
 40036,
 40039,
 40041,
 40050,
 40051,
 40055,
 40062,
 40067,
 40071,
 40078,
 40084,
 40088,
 40114,
 40118,
 40119,
 40134,
 50002,
 50006,
 50007,
 50009,
 50013,
 50014,
 50017,
 50022,
 50025,
 50026,
 50030,
 50036,
 50038,
 50039,
 50042,
 50043,
 50045,
 50047,
 50055,
 50056,
 50057,
 50058,
 50060,
 50063,
 50069,
 50077,
 50078,
 50082,
 50084,
 50090,
 50093,
 50099,
 50100,
 50101,
 50103,
 50104,
 50107,
 50108,
 50110,
 50112,
 50115,
 50116,
 50118,
 50121,
 50124,
 50125,
 50126,
 50127,
 50128,
 50129,
 50132,
 50133,
 50136,
 50145,
 50149,
 50150,
 50152,
 50153,
 50159,
 50167,
 50168,
 50169,
 50174,
 50179,
 50180,
 50191,
 50194,
 50195,
 50197,
 50222,
 50224,
 50225,
 50226,
 50228,
 50231,
 50232,
 50235,
 50236,
 50238,
 50239,
 50242,
 50243,
 50245,
 50248,
 50254,
 50261,
 50262,
 50272,
 50276,
 50278,
 50279,
 50280,
 50281,
 50289,
 50290,
 50291,
 50295,
 50296,
 50298,
 50300,
 50301,
 50305,
 50308,
 50309,
 50320,
 50324,
 50327,
 50329,
 50334,
 50335,
 50336,
 50342,
 50348,
 50350,
 50351,
 50352,
 50353,
 50359,
 50360,
 50367,
 50380,
 50382,
 50390,
 50393,
 50394,
 50396,
 50414,
 50426,
 50438,
 50441,
 50444,
 50454,
 50455,
 50457,
 50464,
 50471,
 50481,
 50485,
 50488,
 50492,
 50496,
 50498,
 50502,
 50503,
 50506,
 50516,
 50523,
 50537,
 50549,
 50557,
 50567,
 50570,
 50573,
 50581,
 50589,
 50590,
 50599,
 50603,
 50608,
 50616,
 50624,
 50625,
 50633,
 50636,
 50678,
 50689,
 50701,
 50739,
 50746,
 50761,
 50764,
 50770,
 50775,
 51329,
 60001,
 60003,
 60004,
 60006,
 60008,
 60009,
 60010,
 60011,
 60012,
 60013,
 60014,
 60015,
 60016,
 60020,
 60022,
 60023,
 60024,
 60027,
 60030,
 60031,
 60032,
 60034,
 60036,
 60044,
 60054,
 60064,
 60065,
 60075,
 60076,
 60100,
 60103,
 60104,
 60112,
 60113,
 60114,
 60119,
 60125,
 70002,
 70003,
 70004,
 70005,
 70006,
 70007,
 70008,
 70010,
 70011,
 70012,
 70016,
 70017,
 70018,
 70019,
 70020,
 70021,
 70022,
 70024,
 70025,
 70027,
 70028,
 70029,
 70031,
 70033,
 70034,
 70035,
 70036,
 80001,
 80003,
 80004,
 80006,
 80007,
 80009,
 90001,
 90003,
 90004,
 90005,
 90006,
 90008,
 90011,
 100001,
 100002,
 100006,
 100007,
 100008,
 100009,
 100012,
 100014,
 100017,
 100018,
 100019,
 100022,
 100023,
 100025,
 100026,
 100028,
 100029,
 100030,
 100032,
 100034,
 100035,
 100038,
 100039,
 100040,
 100043,
 100044,
 100045,
 100046,
 100047,
 100050,
 100051,
 100052,
 100053,
 100054,
 100057,
 100062,
 100063,
 100067,
 100068,
 100069,
 100070,
 100071,
 100072,
 100073,
 100075,
 100080,
 100084,
 100086,
 100087,
 100088,
 100090,
 100092,
 100093,
 100099,
 100105,
 100107,
 100109,
 100110,
 100113,
 100117,
 100118,
 100122,
 100124,
 100125,
 100126,
 100127,
 100128,
 100131,
 100132,
 100135,
 100137,
 100140,
 100142,
 100150,
 100151,
 100154,
 100156,
 100157,
 100161,
 100166,
 100167,
 100168,
 100173,
 100176,
 100177,
 100179,
 100181,
 100183,
 100191,
 100200,
 100204,
 100206,
 100209,
 100212,
 100213,
 100217,
 100220,
 100223,
 100226,
 100230,
 100231,
 100232,
 100236,
 100238,
 100242,
 100243,
 100244,
 100246,
 100248,
 100249,
 100252,
 100253,
 100254,
 100255,
 100256,
 100258,
 100259,
 100260,
 100264,
 100265,
 100266,
 100267,
 100269,
 100275,
 100276,
 100281,
 100285,
 100286,
 100287,
 100289,
 100290,
 100291,
 100292,
 100296,
 100299,
 100302,
 100307,
 100315,
 100316,
 100319,
 100320,
 100321,
 110001,
 110002,
 110003,
 110005,
 110006,
 110007,
 110008,
 110010,
 110011,
 110015,
 110016,
 110018,
 110023,
 110024,
 110025,
 110028,
 110029,
 110030,
 110031,
 110032,
 110034,
 110035,
 110036,
 110038,
 110041,
 110042,
 110043,
 110044,
 110051,
 110054,
 110064,
 110069,
 110074,
 110075,
 110076,
 110078,
 110079,
 110082,
 110083,
 110087,
 110089,
 110091,
 110095,
 110104,
 110105,
 110107,
 110115,
 110122,
 110124,
 110125,
 110128,
 110129,
 110135,
 110143,
 110146,
 110150,
 110161,
 110164,
 110165,
 110168,
 110177,
 110184,
 110191,
 110192,
 110198,
 110201,
 110215,
 110225,
 110226,
 110229,
 110230,
 120001,
 120002,
 120005,
 120006,
 120007,
 120014,
 120022,
 120026,
 130002,
 130003,
 130006,
 130007,
 130013,
 130014,
 130018,
 130025,
 130028,
 130049,
 140001,
 140002,
 140007,
 140008,
 140010,
 140011,
 140012,
 140013,
 140015,
 140018,
 140029,
 140030,
 140032,
 140034,
 140040,
 140043,
 140046,
 140048,
 140049,
 140052,
 140053,
 140054,
 140058,
 140062,
 140063,
 140064,
 140065,
 140067,
 140080,
 140082,
 140084,
 140088,
 140089,
 140091,
 140093,
 140101,
 140110,
 140113,
 140114,
 140115,
 140116,
 140117,
 140118,
 140119,
 140120,
 140122,
 140124,
 140125,
 140127,
 140130,
 140133,
 140135,
 140143,
 140148,
 140150,
 140155,
 140158,
 140160,
 140161,
 140162,
 140164,
 140166,
 140172,
 140174,
 140176,
 140177,
 140179,
 140180,
 140182,
 140184,
 140185,
 140186,
 140187,
 140189,
 140191,
 140200,
 140202,
 140208,
 140209,
 140211,
 140213,
 140217,
 140223,
 140224,
 140228,
 140231,
 140233,
 140234,
 140239,
 140240,
 140242,
 140250,
 140251,
 140252,
 140258,
 140275,
 140276,
 140280,
 140281,
 140286,
 140288,
 140289,
 140290,
 140291,
 140292,
 140294,
 140304,
 150001,
 150002,
 150004,
 150005,
 150006,
 150007,
 150008,
 150009,
 150010,
 150011,
 150012,
 150015,
 150017,
 150018,
 150021,
 150022,
 150023,
 150024,
 150026,
 150030,
 150034,
 150035,
 150037,
 150042,
 150044,
 150045,
 150046,
 150047,
 150048,
 150051,
 150056,
 150057,
 150058,
 150059,
 150065,
 150069,
 150072,
 150074,
 150075,
 150076,
 150082,
 150084,
 150086,
 150088,
 150089,
 150090,
 150097,
 150100,
 150104,
 150109,
 150112,
 150113,
 150115,
 150125,
 150126,
 150128,
 150133,
 150150,
 150157,
 150158,
 150161,
 150162,
 150165,
 150169,
 150173,
 150176,
 160005,
 160016,
 160024,
 160028,
 160029,
 160030,
 160032,
 160033,
 160045,
 160047,
 160057,
 160058,
 160064,
 160067,
 160079,
 160080,
 160082,
 160083,
 160089,
 160110,
 160117,
 160122,
 160124,
 160146,
 160153,
 170006,
 170012,
 170013,
 170014,
 170016,
 170017,
 170020,
 170023,
 170027,
 170040,
 170049,
 170068,
 170074,
 170086,
 170103,
 170104,
 170120,
 170122,
 170123,
 170137,
 170142,
 170145,
 170146,
 170176,
 170182,
 170185,
 170191,
 170197,
 170200,
 180001,
 180002,
 180004,
 180005,
 180009,
 180010,
 180011,
 180012,
 180013,
 180016,
 180017,
 180018,
 180019,
 180021,
 180024,
 180025,
 180027,
 180029,
 180035,
 180036,
 180038,
 180040,
 180044,
 180045,
 180048,
 180049,
 180050,
 180051,
 180056,
 180064,
 180067,
 180069,
 180070,
 180078,
 180080,
 180087,
 180088,
 180092,
 180093,
 180101,
 180102,
 180103,
 180104,
 180116,
 180124,
 180127,
 180128,
 180130,
 180132,
 180138,
 180141,
 180143,
 190002,
 190004,
 190005,
 190007,
 190008,
 190013,
 190014,
 190015,
 190017,
 190019,
 190020,
 190026,
 190027,
 190036,
 190039,
 190040,
 190041,
 190045,
 190046,
 190053,
 190054,
 190060,
 190064,
 190065,
 190098,
 190102,
 190111,
 190125,
 190144,
 190146,
 190160,
 190164,
 190167,
 190176,
 190177,
 190183,
 190202,
 190204,
 190205,
 190236,
 190250,
 190274,
 200001,
 200008,
 200009,
 200018,
 200019,
 200020,
 200021,
 200024,
 200031,
 200033,
 200034,
 200037,
 200039,
 200041,
 200050,
 200063,
 220001,
 220002,
 220008,
 220010,
 220011,
 220012,
 220015,
 220016,
 220017,
 220019,
 220020,
 220024,
 220029,
 220031,
 220033,
 220035,
 220036,
 220046,
 220049,
 220052,
 220060,
 220063,
 220065,
 220066,
 220070,
 220071,
 220073,
 220074,
 220077,
 220080,
 220083,
 220084,
 220086,
 220090,
 220095,
 220098,
 220100,
 220101,
 220105,
 220108,
 220110,
 220111,
 220116,
 220119,
 220126,
 220135,
 220163,
 220171,
 220175,
 220176,
 230002,
 230003,
 230005,
 230017,
 230019,
 230020,
 230021,
 230022,
 230024,
 230029,
 230030,
 230031,
 230035,
 ...]

In [85]:
indexs= provider_id.index(i)
indexs

60

In [86]:
correlation_provider_id = correlation_matrix[indexs]
correlation_provider_id.shape

(2297,)

In [87]:
#recommending n from the list
Recommend = list(X.index[correlation_provider_id > 0.90])
 

a = Recommend[0:5]
a

[30016]

In [88]:
#splitting train and test data to find accuracy value
x=DF.loc[:,['Hospital overall rating']]
x
y=x[:20000]
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.4,random_state=100)

In [89]:
#using SVC classifier
from sklearn.svm import SVC
from sklearn import metrics
svc=SVC() 
svc.fit(X_train,y_train)
y_pred=svc.predict(X_test)
#Accuracy value
print('Accuracy Score:')
print(metrics.accuracy_score(y_test,y_pred))

Accuracy Score:
1.0

C:\Users\varsh\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [90]:
#converting to float value
from sklearn.model_selection import train_test_split
y = pd.to_numeric(DF['Hospital overall rating'], downcast='float')
y.values
providerId = pd.to_numeric(DF['Provider ID'], downcast='float')
providerId

0        10001.0
1        10005.0
2        10006.0
5        10011.0
6        10012.0
          ...
4776    670077.0
4778    670079.0
4779    670080.0
4780    670082.0
4784    670088.0
Name: Provider ID, Length: 2297, dtype: float32

In [91]:
#splitting the dataset
import sklearn.model_selection as model_selection
X_train, X_test, y_train, y_test = model_selection.train_test_split(providerId, y, test_size=0.4,random_state=109)

In [92]:
#reshape the feature extracted
X_train = X_train.values
X = X_train.reshape(-1, 1)
X_test = X_test.values
y_train = y_train.values
y = y_train.reshape(-1, 1)
y_test = y_test.values

In [93]:
#importing 
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.dummy import DummyClassifier
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, recall_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.cluster import KMeans
from sklearn.naive_bayes import GaussianNB
import collections

In [94]:
classifiers = {
    "Support Vector Classifier": SVC()
}

In [95]:
#Determining accuracy
from sklearn.model_selection import cross_val_score
for key, classifier in classifiers.items():
    classifier.fit(X , y)
    acc_score = cross_val_score(classifier, X, y, cv=5)
    print("Classifiers: ", classifier.__class__.__name__, "Has a accuracy score of", round(acc_score.mean(), 2), "accuracy score")
    print("Classifiers: ", classifier.__class__.__name__, "Has a accuracy score percentage of", round(acc_score.mean(), 2) * 100, " % accuracy percentage")

C:\Users\varsh\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\varsh\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\varsh\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\varsh\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\varsh\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

Classifiers:  SVC Has a accuracy score of 0.45 accuracy score
Classifiers:  SVC Has a accuracy score percentage of 45.0  % accuracy percentage

C:\Users\varsh\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [96]:
#knn

In [100]:
from scipy.sparse import csr_matrix
from sklearn.neighbors import NearestNeighbors
knn = np.array(utility_value.values)
knn.size
nbrs = NearestNeighbors(n_neighbors=3, algorithm='ball_tree').fit(knn)
distances, indices = nbrs.kneighbors(knn)

In [101]:
print(indices)

[[   0  120   12]
 [   1  120   12]
 [   2  120   12]
 ...
 [2169   12  120]
 [2170   12  120]
 [2171  120   12]]

In [103]:
classifiers = {
     "KNearest": KNeighborsClassifier()
}

In [104]:
#accuracy value with knearest classifier
from sklearn.model_selection import cross_val_score
for key, classifier in classifiers.items():
    classifier.fit(X , y)
    acc_score = cross_val_score(classifier, X, y, cv=5)
    print("Classifiers: ", classifier.__class__.__name__, "Has a accuracy score of", round(acc_score.mean(), 2), "accuracy score")
    print("Classifiers: ", classifier.__class__.__name__, "Has a accuracy score percentage of", round(acc_score.mean(), 2) * 100, " % accuracy percentage")

Classifiers:  KNeighborsClassifier Has a accuracy score of 0.4 accuracy score
Classifiers:  KNeighborsClassifier Has a accuracy score percentage of 40.0  % accuracy percentage

C:\Users\varsh\anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\varsh\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:515: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\varsh\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:515: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\varsh\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:515: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\varsh\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:515: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\varsh\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:515: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)